# 运行模式(debug:调试,test:测试,release:正式)
run_mode = "release"
# 静态站点目录(也可以启动服务时使用-www指定)
www = ""

[http]
# http监听地址
host = "0.0.0.0"
# http监听端口
port = 10088
# 证书路径
cert_file = ""
# 证书密钥
key_file = ""
# http优雅关闭等待超时时长(单位秒)
shutdown_timeout = 30

[log]
# 是否开启 debug 模式
debug = false
# 日志输出
output = false
# 指定日志输出的文件路径
path = "data/logs/go/user-server"

[jwt]
# 是否启用
enable = true
# 签名方式(支持：HS512/HS384/HS512)
signing_method = "HS512"
# 签名key
signing_key = "user-server"
# 过期时间（单位秒）
expired = 7200
# 存储(支持：file/redis)
store = "file"
# 文件路径
file_path = "../../target/jwt.db"
# redis数据库(如果存储方式是redis，则指定存储的数据库)
redis_db = 10
# 存储到redis数据库中的键名前缀
redis_prefix = "auth_"